# Alexa Prompts Language Constants
SKILL_NAME = "SKILL_NAME"
LAUNCH_MESSAGE = "LAUNCH_MESSAGE"
HELP_MESSAGE = "HELP_MESSAGE"
HELP_REPROMPT = "HELP_REPROMPT"
FALLBACK_MESSAGE = "FALLBACK_MESSAGE"
FALLBACK_REPROMPT = "FALLBACK_REPROMPT"
CONTEXT_CLEAR_RESPONSE = "CONTEXT_CLEAR_RESPONSE"
ERROR_MESSAGE = "ERROR_MESSAGE"
STOP_MESSAGE = "STOP_MESSAGE"
QUESTION_RESPONSE = "QUESTION_RESPONSE"
QUESTION_UNFINISHED_RESPONSE = "QUESTION_UNFINISHED_RESPONSE"
QUESTION_INTENT_ERROR_MESSAGE = "QUESTION_INTENT_ERROR_MESSAGE"
QUESTION_INTENT_OPENAI_ERROR_MESSAGE = "QUESTION_INTENT_OPENAI_ERROR_MESSAGE"
SUBSCRIPTION_UPSELL = "SUBSCRIPTION_UPSELL"
ISP_PURCHASE_DECLINED_MESSAGE = "ISP_PURCHASE_DECLINED_MESSAGE"
ISP_PURCHASE_ERROR_MESSAGE = "ISP_PURCHASE_ERROR_MESSAGE"
ISP_CANCEL_DECLINED_MESSAGE = "ISP_CANCEL_DECLINED_MESSAGE"
ISP_CANCEL_ERROR_MESSAGE = "ISP_CANCEL_ERROR_MESSAGE"

SPEECHCONS_ACK = [
    "ack",
    "all righty",
    "alrighty",
    "as you wish",
    "gotcha",
    "you bet",
    "yabba dabba doo"
]
